[2022-05-26 21:00:53,525] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: trigger_rule.task_1 scheduled__2022-05-25T00:00:00+00:00 [queued]>
[2022-05-26 21:00:53,641] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: trigger_rule.task_1 scheduled__2022-05-25T00:00:00+00:00 [queued]>
[2022-05-26 21:00:53,643] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-26 21:00:53,646] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-26 21:00:53,660] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-26 21:00:53,942] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): task_1> on 2022-05-25 00:00:00+00:00
[2022-05-26 21:00:54,018] {standard_task_runner.py:52} INFO - Started process 404 to run task
[2022-05-26 21:00:54,093] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'trigger_rule', 'task_1', 'scheduled__2022-05-25T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/trigger_rule.py', '--cfg-path', '/tmp/tmp0sl2rx2l', '--error-file', '/tmp/tmp23ugkmqo']
[2022-05-26 21:00:54,121] {standard_task_runner.py:80} INFO - Job 12: Subtask task_1
[2022-05-26 21:00:55,792] {task_command.py:369} INFO - Running <TaskInstance: trigger_rule.task_1 scheduled__2022-05-25T00:00:00+00:00 [running]> on host 2fe522ea8532
[2022-05-26 21:01:00,009] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_rule
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2022-05-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-25T00:00:00+00:00
[2022-05-26 21:01:00,073] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-26 21:01:00,101] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'exit 0']
[2022-05-26 21:01:00,398] {subprocess.py:85} INFO - Output:
[2022-05-26 21:01:00,650] {subprocess.py:96} INFO - Command exited with return code 0
[2022-05-26 21:01:01,517] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=trigger_rule, task_id=task_1, execution_date=20220525T000000, start_date=20220526T210053, end_date=20220526T210101
[2022-05-26 21:01:02,305] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-26 21:01:03,037] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
