[2022-05-26 16:13:02,748] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: book_db.check_api 2022-05-25T00:00:00+00:00 [queued]>
[2022-05-26 16:13:02,806] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: book_db.check_api 2022-05-25T00:00:00+00:00 [queued]>
[2022-05-26 16:13:02,807] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2022-05-26 16:13:02,808] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2022-05-26 16:13:02,809] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2022-05-26 16:13:02,948] {taskinstance.py:1107} INFO - Executing <Task(HttpSensor): check_api> on 2022-05-25T00:00:00+00:00
[2022-05-26 16:13:02,995] {standard_task_runner.py:52} INFO - Started process 27 to run task
[2022-05-26 16:13:03,026] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'book_db', 'check_api', '2022-05-25T00:00:00+00:00', '--job-id', '36', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/books_db.py', '--cfg-path', '/tmp/tmpo87udkf5', '--error-file', '/tmp/tmpccq0_gjx']
[2022-05-26 16:13:03,065] {standard_task_runner.py:77} INFO - Job 36: Subtask check_api
[2022-05-26 16:13:03,982] {logging_mixin.py:104} INFO - Running <TaskInstance: book_db.check_api 2022-05-25T00:00:00+00:00 [running]> on host 0f09442c242c
[2022-05-26 16:13:04,766] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=book_db
AIRFLOW_CTX_TASK_ID=check_api
AIRFLOW_CTX_EXECUTION_DATE=2022-05-25T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-25T00:00:00+00:00
[2022-05-26 16:13:04,783] {http.py:101} INFO - Poking: new
[2022-05-26 16:13:04,912] {base.py:69} INFO - Using connection to: id: book_api. Host: https://api.itbook.store/1.0/, Port: None, Schema: , Login: , Password: None, extra: {}
[2022-05-26 16:13:04,925] {http.py:140} INFO - Sending 'GET' to url: https://api.itbook.store/1.0/new
[2022-05-26 16:13:06,245] {base.py:248} INFO - Success criteria met. Exiting.
[2022-05-26 16:13:06,452] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=book_db, task_id=check_api, execution_date=20220525T000000, start_date=20220526T161302, end_date=20220526T161306
[2022-05-26 16:13:06,825] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-05-26 16:13:06,898] {local_task_job.py:151} INFO - Task exited with return code 0
