[2022-05-22 21:37:55,762] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: book_db.check_api 2022-05-22T21:37:50.631574+00:00 [queued]>
[2022-05-22 21:37:55,784] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: book_db.check_api 2022-05-22T21:37:50.631574+00:00 [queued]>
[2022-05-22 21:37:55,785] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2022-05-22 21:37:55,786] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2022-05-22 21:37:55,787] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2022-05-22 21:37:55,857] {taskinstance.py:1107} INFO - Executing <Task(HttpSensor): check_api> on 2022-05-22T21:37:50.631574+00:00
[2022-05-22 21:37:55,862] {standard_task_runner.py:52} INFO - Started process 123 to run task
[2022-05-22 21:37:55,869] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'book_db', 'check_api', '2022-05-22T21:37:50.631574+00:00', '--job-id', '6', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/books_db.py', '--cfg-path', '/tmp/tmpi4ebyh97', '--error-file', '/tmp/tmpypnhwaub']
[2022-05-22 21:37:55,870] {standard_task_runner.py:77} INFO - Job 6: Subtask check_api
[2022-05-22 21:37:56,061] {logging_mixin.py:104} INFO - Running <TaskInstance: book_db.check_api 2022-05-22T21:37:50.631574+00:00 [running]> on host 929b3ffb0527
[2022-05-22 21:37:56,316] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=book_db
AIRFLOW_CTX_TASK_ID=check_api
AIRFLOW_CTX_EXECUTION_DATE=2022-05-22T21:37:50.631574+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-22T21:37:50.631574+00:00
[2022-05-22 21:37:56,319] {http.py:101} INFO - Poking: new
[2022-05-22 21:37:56,335] {base.py:69} INFO - Using connection to: id: book_api. Host: https://api.itbook.store/1.0/, Port: None, Schema: , Login: , Password: None, extra: {}
[2022-05-22 21:37:56,341] {http.py:140} INFO - Sending 'GET' to url: https://api.itbook.store/1.0/new
[2022-05-22 21:37:57,168] {base.py:248} INFO - Success criteria met. Exiting.
[2022-05-22 21:37:57,233] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=book_db, task_id=check_api, execution_date=20220522T213750, start_date=20220522T213755, end_date=20220522T213757
[2022-05-22 21:37:57,473] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-05-22 21:37:57,530] {local_task_job.py:151} INFO - Task exited with return code 0
