[2022-05-22 22:03:58,082] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: book_db.check_api 2022-05-22T22:03:52.975384+00:00 [queued]>
[2022-05-22 22:03:58,189] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: book_db.check_api 2022-05-22T22:03:52.975384+00:00 [queued]>
[2022-05-22 22:03:58,195] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2022-05-22 22:03:58,197] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2022-05-22 22:03:58,199] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2022-05-22 22:03:58,588] {taskinstance.py:1107} INFO - Executing <Task(HttpSensor): check_api> on 2022-05-22T22:03:52.975384+00:00
[2022-05-22 22:03:58,593] {standard_task_runner.py:52} INFO - Started process 109 to run task
[2022-05-22 22:03:58,602] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'book_db', 'check_api', '2022-05-22T22:03:52.975384+00:00', '--job-id', '3', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/books_db.py', '--cfg-path', '/tmp/tmpns34kq42', '--error-file', '/tmp/tmpqtewh7rz']
[2022-05-22 22:03:58,606] {standard_task_runner.py:77} INFO - Job 3: Subtask check_api
[2022-05-22 22:03:58,936] {logging_mixin.py:104} INFO - Running <TaskInstance: book_db.check_api 2022-05-22T22:03:52.975384+00:00 [running]> on host 929b3ffb0527
[2022-05-22 22:03:59,458] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=book_db
AIRFLOW_CTX_TASK_ID=check_api
AIRFLOW_CTX_EXECUTION_DATE=2022-05-22T22:03:52.975384+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-22T22:03:52.975384+00:00
[2022-05-22 22:03:59,466] {http.py:101} INFO - Poking: new
[2022-05-22 22:03:59,497] {base.py:69} INFO - Using connection to: id: book_api. Host: https://api.itbook.store/1.0/, Port: None, Schema: , Login: , Password: None, extra: {}
[2022-05-22 22:03:59,501] {http.py:140} INFO - Sending 'GET' to url: https://api.itbook.store/1.0/new
[2022-05-22 22:04:00,014] {base.py:248} INFO - Success criteria met. Exiting.
[2022-05-22 22:04:00,035] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=book_db, task_id=check_api, execution_date=20220522T220352, start_date=20220522T220358, end_date=20220522T220400
[2022-05-22 22:04:00,254] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-05-22 22:04:00,307] {local_task_job.py:151} INFO - Task exited with return code 0
