[2022-05-31 19:15:50,985] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: book_db.store_books 2022-05-28T00:00:00+00:00 [queued]>
[2022-05-31 19:15:51,017] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: book_db.store_books 2022-05-28T00:00:00+00:00 [queued]>
[2022-05-31 19:15:51,019] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2022-05-31 19:15:51,020] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2022-05-31 19:15:51,021] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2022-05-31 19:15:51,091] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): store_books> on 2022-05-28T00:00:00+00:00
[2022-05-31 19:15:51,095] {standard_task_runner.py:52} INFO - Started process 49 to run task
[2022-05-31 19:15:51,102] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'book_db', 'store_books', '2022-05-28T00:00:00+00:00', '--job-id', '52', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/books_db.py', '--cfg-path', '/tmp/tmpxhzda2qh', '--error-file', '/tmp/tmpy8u83glj']
[2022-05-31 19:15:51,104] {standard_task_runner.py:77} INFO - Job 52: Subtask store_books
[2022-05-31 19:15:51,191] {logging_mixin.py:104} INFO - Running <TaskInstance: book_db.store_books 2022-05-28T00:00:00+00:00 [running]> on host 7a1d03ce9394
[2022-05-31 19:15:51,328] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=book_db
AIRFLOW_CTX_TASK_ID=store_books
AIRFLOW_CTX_EXECUTION_DATE=2022-05-28T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-28T00:00:00+00:00
[2022-05-31 19:15:51,357] {logging_mixin.py:104} WARNING - /home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py:2779 UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
[2022-05-31 19:15:51,434] {python.py:151} INFO - Done. Returned value was: None
[2022-05-31 19:15:51,453] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=book_db, task_id=store_books, execution_date=20220528T000000, start_date=20220531T191550, end_date=20220531T191551
[2022-05-31 19:15:51,558] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-31 19:15:51,603] {local_task_job.py:151} INFO - Task exited with return code 0
