[2022-05-24 11:22:07,929] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: book_db.check_api 2022-05-23T00:00:00+00:00 [queued]>
[2022-05-24 11:22:08,009] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: book_db.check_api 2022-05-23T00:00:00+00:00 [queued]>
[2022-05-24 11:22:08,010] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2022-05-24 11:22:08,011] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2022-05-24 11:22:08,016] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2022-05-24 11:22:08,121] {taskinstance.py:1107} INFO - Executing <Task(HttpSensor): check_api> on 2022-05-23T00:00:00+00:00
[2022-05-24 11:22:08,141] {standard_task_runner.py:52} INFO - Started process 26 to run task
[2022-05-24 11:22:08,203] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'book_db', 'check_api', '2022-05-23T00:00:00+00:00', '--job-id', '30', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/books_db.py', '--cfg-path', '/tmp/tmpvbflithf', '--error-file', '/tmp/tmpsl9ka2u8']
[2022-05-24 11:22:08,212] {standard_task_runner.py:77} INFO - Job 30: Subtask check_api
[2022-05-24 11:22:08,551] {logging_mixin.py:104} INFO - Running <TaskInstance: book_db.check_api 2022-05-23T00:00:00+00:00 [running]> on host 0f09442c242c
[2022-05-24 11:22:08,875] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=book_db
AIRFLOW_CTX_TASK_ID=check_api
AIRFLOW_CTX_EXECUTION_DATE=2022-05-23T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-23T00:00:00+00:00
[2022-05-24 11:22:08,882] {http.py:101} INFO - Poking: new
[2022-05-24 11:22:08,931] {base.py:69} INFO - Using connection to: id: book_api. Host: https://api.itbook.store/1.0/, Port: None, Schema: , Login: , Password: None, extra: {}
[2022-05-24 11:22:08,936] {http.py:140} INFO - Sending 'GET' to url: https://api.itbook.store/1.0/new
[2022-05-24 11:22:09,459] {base.py:248} INFO - Success criteria met. Exiting.
[2022-05-24 11:22:09,487] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=book_db, task_id=check_api, execution_date=20220523T000000, start_date=20220524T112207, end_date=20220524T112209
[2022-05-24 11:22:09,722] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-05-24 11:22:09,850] {local_task_job.py:151} INFO - Task exited with return code 0
