[2022-05-22 22:18:49,839] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: book_db.save_books 2022-05-22T22:18:20.565412+00:00 [queued]>
[2022-05-22 22:18:49,863] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: book_db.save_books 2022-05-22T22:18:20.565412+00:00 [queued]>
[2022-05-22 22:18:49,864] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2022-05-22 22:18:49,866] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2022-05-22 22:18:49,867] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2022-05-22 22:18:49,929] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): save_books> on 2022-05-22T22:18:20.565412+00:00
[2022-05-22 22:18:49,933] {standard_task_runner.py:52} INFO - Started process 42 to run task
[2022-05-22 22:18:49,938] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'book_db', 'save_books', '2022-05-22T22:18:20.565412+00:00', '--job-id', '18', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/books_db.py', '--cfg-path', '/tmp/tmpnwbn9m2j', '--error-file', '/tmp/tmpzhw1c5j9']
[2022-05-22 22:18:49,940] {standard_task_runner.py:77} INFO - Job 18: Subtask save_books
[2022-05-22 22:18:50,031] {logging_mixin.py:104} INFO - Running <TaskInstance: book_db.save_books 2022-05-22T22:18:20.565412+00:00 [running]> on host 0f09442c242c
[2022-05-22 22:18:50,160] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=book_db
AIRFLOW_CTX_TASK_ID=save_books
AIRFLOW_CTX_EXECUTION_DATE=2022-05-22T22:18:20.565412+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-22T22:18:20.565412+00:00
[2022-05-22 22:18:50,196] {python.py:151} INFO - Done. Returned value was: None
[2022-05-22 22:18:50,216] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=book_db, task_id=save_books, execution_date=20220522T221820, start_date=20220522T221849, end_date=20220522T221850
[2022-05-22 22:18:50,332] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-05-22 22:18:50,353] {local_task_job.py:151} INFO - Task exited with return code 0
