[2022-05-22 21:38:13,096] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: book_db.save_books 2022-05-22T21:37:50.631574+00:00 [queued]>
[2022-05-22 21:38:13,154] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: book_db.save_books 2022-05-22T21:37:50.631574+00:00 [queued]>
[2022-05-22 21:38:13,156] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2022-05-22 21:38:13,158] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2022-05-22 21:38:13,160] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2022-05-22 21:38:13,328] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): save_books> on 2022-05-22T21:37:50.631574+00:00
[2022-05-22 21:38:13,332] {standard_task_runner.py:52} INFO - Started process 138 to run task
[2022-05-22 21:38:13,342] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'book_db', 'save_books', '2022-05-22T21:37:50.631574+00:00', '--job-id', '9', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/books_db.py', '--cfg-path', '/tmp/tmp4i43ntuv', '--error-file', '/tmp/tmp4jok851h']
[2022-05-22 21:38:13,345] {standard_task_runner.py:77} INFO - Job 9: Subtask save_books
[2022-05-22 21:38:13,495] {logging_mixin.py:104} INFO - Running <TaskInstance: book_db.save_books 2022-05-22T21:37:50.631574+00:00 [running]> on host 929b3ffb0527
[2022-05-22 21:38:13,769] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=book_db
AIRFLOW_CTX_TASK_ID=save_books
AIRFLOW_CTX_EXECUTION_DATE=2022-05-22T21:37:50.631574+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-22T21:37:50.631574+00:00
[2022-05-22 21:38:13,821] {python.py:151} INFO - Done. Returned value was: None
[2022-05-22 21:38:13,849] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=book_db, task_id=save_books, execution_date=20220522T213750, start_date=20220522T213813, end_date=20220522T213813
[2022-05-22 21:38:14,038] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-05-22 21:38:14,060] {local_task_job.py:151} INFO - Task exited with return code 0
