[2022-05-26 21:01:35,267] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: trigger_rule.task_7 scheduled__2022-05-25T00:00:00+00:00 [queued]>
[2022-05-26 21:01:35,429] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: trigger_rule.task_7 scheduled__2022-05-25T00:00:00+00:00 [queued]>
[2022-05-26 21:01:35,436] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-26 21:01:35,438] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-26 21:01:35,448] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-26 21:01:35,750] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): task_7> on 2022-05-25 00:00:00+00:00
[2022-05-26 21:01:35,836] {standard_task_runner.py:52} INFO - Started process 594 to run task
[2022-05-26 21:01:35,895] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'trigger_rule', 'task_7', 'scheduled__2022-05-25T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/trigger_rule.py', '--cfg-path', '/tmp/tmplm_frt5n', '--error-file', '/tmp/tmpon216d4w']
[2022-05-26 21:01:35,945] {standard_task_runner.py:80} INFO - Job 18: Subtask task_7
[2022-05-26 21:01:36,659] {task_command.py:369} INFO - Running <TaskInstance: trigger_rule.task_7 scheduled__2022-05-25T00:00:00+00:00 [running]> on host 2fe522ea8532
[2022-05-26 21:01:37,541] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2022-05-26 21:01:37,623] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 594. PIDs of all processes in the group: [594]
[2022-05-26 21:01:37,632] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 594
[2022-05-26 21:01:37,934] {process_utils.py:75} INFO - Process psutil.Process(pid=594, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='21:01:35') (594) terminated with exit code Negsignal.SIGTERM
[2022-05-26 21:01:38,078] {local_task_job.py:156} INFO - Task exited with return code 143
